[project]
name = 'Decentralized-Commercial-Insurance-Claims'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.adjuster-assignment]
path = 'contracts/adjuster-assignment.clar'
clarity_version = 2
epoch = 2.5

[contracts.incident-documentation]
path = 'contracts/incident-documentation.clar'
clarity_version = 2
epoch = 2.5

[contracts.policy-verification]
path = 'contracts/policy-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.settlement]
path = 'contracts/settlement.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
